# Generated by Django 5.2.7 on 2025-10-23 04:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='URL de YouTube')),
                ('file_path', models.FileField(upload_to='songs/', verbose_name='Archivo MP3')),
                ('duration', models.FloatField(default=0, verbose_name='Duración (segundos)')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de agregado')),
                ('play_count', models.IntegerField(default=0, verbose_name='Reproducciones')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=False, verbose_name='Playlist activa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='CurrentPlayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Clave de sesión')),
                ('current_position', models.IntegerField(default=0, verbose_name='Posición en playlist')),
                ('is_playing', models.BooleanField(default=False, verbose_name='Reproduciendo')),
                ('volume', models.FloatField(default=0.5, verbose_name='Volumen')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('current_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.playlist', verbose_name='Playlist actual')),
                ('current_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.song', verbose_name='Canción actual')),
            ],
            options={
                'verbose_name': 'Estado de Reproducción',
                'verbose_name_plural': 'Estados de Reproducción',
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, verbose_name='Posición')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de agregado')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playlist', verbose_name='Playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.song', verbose_name='Canción')),
            ],
            options={
                'verbose_name': 'Item de Playlist',
                'verbose_name_plural': 'Items de Playlist',
                'ordering': ['position'],
                'unique_together': {('playlist', 'position')},
            },
        ),
    ]
