# Generated by Django 5.2.7 on 2025-10-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_path',
            field=models.CharField(max_length=500, verbose_name='Archivo MP3'),
        ),
    ]
